### ISSUE TITLE
biome change effect

### ISSUE THREAD

**Issue by rudde0** [cheeezburga/SkWE#2]
Hello,

Could you add some effect like `set biomes between %location% and %location% to %biome%`?

Thanks for consideration

**Comment by cheeezburga** [comment]
Had a look around and this should be a fairly easy effect to add! I'll keep you updated, but this should be good to go for the next update.

**Comment by cheeezburga** [comment]
@rudde0 would being able to set the biome of a block (or blocks) be useful, or just setting the biome of a region like all the other effects?
