### ISSUE TITLE
Schematic pasting error.

### ISSUE THREAD

**Issue by Com2486** [cheeezburga/SkWE#5]
I found this on SkriptHub and I wanted to use it to paste a default "island" in a world. 
Here's my script.
```
command /test:
	trigger:
		set {_location} to location of block at location of player # I've tried a couple other things as well, this was my latest attempt
		paste schematic named "mechanium_island_small" at {_location}
```

This script generates the in-game error 'An internal error occured[...]'
and the console error is attached in [error.txt](https://github.com/user-attachments/files/16520103/error.txt)

**Comment by Com2486** [comment]
More info will be provided upon request

**Comment by cheeezburga** [comment]
I'll have a look into it, but I'll need a genuine error.txt, not whatever that is

**Comment by Com2486** [comment]
Well shit. Look at me trying to be professional lol, I pasted the wrong file.
[This one should be correct](https://github.com/user-attachments/files/16536395/error.txt)
